# Generated by Django 5.2.8 on 2025-12-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='STOCK_ALERT', max_length=50)),
                ('level', models.CharField(choices=[('LOW', 'Stock bas'), ('ZERO', 'Stock épuisé')], max_length=10)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('stock_id', models.IntegerField(blank=True, null=True)),
                ('piece_id', models.IntegerField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('min_quantity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UNREAD', 'Non lu'), ('READ', 'Lu')], default='UNREAD', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
